### ISSUE TITLE
Minor README bug

### ISSUE THREAD

**Issue by lunarserge** [lunarserge/facere-sensum#50]
README should use 'facere-sensum', not 'facere_sensum' in the 'Usage' section

**Comment by cl7paBka** [comment]
Hi, I have fixed the typo in the README as mentioned in this issue and have created a pull request [#51](https://github.com/lunarserge/facere-sensum/pull/51). Could you please review and approve it when you have time?

**Comment by lunarserge** [comment]
Fixed by #51
